version: "3"
services:
  api:
    image: jeffrygonzalez/employeesapi:sep21
    ports: 
      - 80:80
    environment: 
      - nodeApi=http://node:3000
      - ConnectionStrings__employees=server=sql;database=employees_docker;user=sa;password=TokyoJoe138!
      - flags:future="true"

  node:
    image: jeffrygonzalez/node-api-on-call:2
    ports:
      - 3000:3000

  sql:
    image: jeffrygonzalez/sqlfor-employees:sep21
    ports:
      - 1433:1433
